export const JOBS = [
    {
      id: 1,
      title: 'Frontend Developer 💻',
      company: 'Tech Corp',
      rating: 4.5,
      location: 'Bangalore, Karnataka',
      jobType: 'Full-Time',
      salary: '₹8,00,000 - ₹12,00,000 per annum',
    },
    {
      id: 2,
      title: 'Backend Developer 🛠️',
      company: 'Code Masters',
      rating: 4.3,
      location: 'Hyderabad, Telangana',
      jobType: 'Full-Time',
      salary: '₹9,00,000 - ₹14,00,000 per annum',
    },
    {
      id: 3,
      title: 'Full Stack Developer 🌐',
      company: 'Innovate Inc',
      rating: 4.8,
      location: 'Pune, Maharashtra',
      jobType: 'Part-Time',
      salary: '₹6,00,000 - ₹9,00,000 per annum',
    },
    {
      id: 4,
      title: 'UI/UX Designer 🎨',
      company: 'Design Studio',
      rating: 4.6,
      location: 'Mumbai, Maharashtra',
      jobType: 'Full-Time',
      salary: '₹7,00,000 - ₹10,00,000 per annum',
    },
    {
      id: 5,
      title: 'DevOps Engineer 🚀',
      company: 'Cloud Ninjas',
      rating: 4.9,
      location: 'Chennai, Tamil Nadu',
      jobType: 'Full-Time',
      salary: '₹12,00,000 - ₹16,00,000 per annum',
    },
    {
      id: 6,
      title: 'Data Scientist 📊',
      company: 'Data Insights',
      rating: 4.7,
      location: 'Delhi, NCR',
      jobType: 'Remote',
      salary: '₹15,00,000 - ₹20,00,000 per annum',
    },
    // {
    //   id: 7,
    //   title: 'Mobile App Developer 📱',
    //   company: 'Appify Solutions',
    //   rating: 4.4,
    //   location: 'Ahmedabad, Gujarat',
    //   jobType: 'Full-Time',
    //   salary: '₹8,50,000 - ₹11,00,000 per annum',
    // },
    // {
    //   id: 8,
    //   title: 'Product Manager 📋',
    //   company: 'Visionary Tech',
    //   rating: 4.2,
    //   location: 'Kolkata, West Bengal',
    //   jobType: 'Full-Time',
    //   salary: '₹14,00,000 - ₹18,00,000 per annum',
    // },
    // {
    //   id: 9,
    //   title: 'QA Engineer ✅',
    //   company: 'Quality First',
    //   rating: 4.3,
    //   location: 'Jaipur, Rajasthan',
    //   jobType: 'Part-Time',
    //   salary: '₹4,50,000 - ₹6,50,000 per annum',
    // },
    // {
    //   id: 10,
    //   title: 'Machine Learning Engineer 🤖',
    //   company: 'AI Hub',
    //   rating: 4.9,
    //   location: 'Coimbatore, Tamil Nadu',
    //   jobType: 'Full-Time',
    //   salary: '₹18,00,000 - ₹22,00,000 per annum',
    // },
    // {
    //   id: 11,
    //   title: 'Cybersecurity Analyst 🔐',
    //   company: 'SecureTech',
    //   rating: 4.6,
    //   location: 'Lucknow, Uttar Pradesh',
    //   jobType: 'Full-Time',
    //   salary: '₹10,00,000 - ₹13,00,000 per annum',
    // },
    // {
    //   id: 12,
    //   title: 'Cloud Architect ☁️',
    //   company: 'CloudWorks',
    //   rating: 4.8,
    //   location: 'Bhubaneswar, Odisha',
    //   jobType: 'Full-Time',
    //   salary: '₹18,00,000 - ₹24,00,000 per annum',
    // },
    // {
    //   id: 13,
    //   title: 'Technical Writer 📝',
    //   company: 'WriteIt',
    //   rating: 4.1,
    //   location: 'Indore, Madhya Pradesh',
    //   jobType: 'Remote',
    //   salary: '₹5,00,000 - ₹7,00,000 per annum',
    // },
    // {
    //   id: 14,
    //   title: 'Game Developer 🎮',
    //   company: 'Game Studio',
    //   rating: 4.7,
    //   location: 'Trivandrum, Kerala',
    //   jobType: 'Full-Time',
    //   salary: '₹9,00,000 - ₹12,00,000 per annum',
    // },
    // {
    //   id: 15,
    //   title: 'Blockchain Developer 🔗',
    //   company: 'Crypto Innovators',
    //   rating: 4.9,
    //   location: 'Gurugram, Haryana',
    //   jobType: 'Remote',
    //   salary: '₹20,00,000 - ₹25,00,000 per annum',
    // },
  ];
  